### ISSUE TITLE
Conda release for 0.3.1

### ISSUE THREAD

**Issue by garfinjm** [will-rowe/artic_tools#15]
Hello,

Our lab wants to switch to 0.3.1 to avoid the segfault issue with 0.3.0 that was patched, but it looks like it's not available in conda yet.

Thanks,
Jake

**Comment by will-rowe** [comment]
Hi Jake,

I'm afraid I've not had much time to get it landed in conda. We were running into some issues:

https://github.com/bioconda/bioconda-recipes/pull/30142

Feel free to have a go getting the conda build to pass, if not I will try and get around to it again soon.

Will

**Comment by garfinjm** [comment]
Looks to be working now. Thanks!
